from typing import Protocol

from app.models import Subscription, User


class EmailService(Protocol):
    async def payment_succeeded(self, user: User, subscription: Subscription) -> None: ...
    async def subscription_upgraded(self, user: User, subscription: Subscription) -> None: ...
    async def subscription_downgraded(self, user: User, subscription: Subscription) -> None: ...
    async def subscription_canceled(self, user: User, subscription: Subscription) -> None: ...
